# Generated by Django 3.2.16 on 2022-11-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_rating'),
        ('wishlist', '0005_auto_20221116_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(related_name='products', to='products.Product'),
        ),
    ]
