# Generated by Django 3.2.16 on 2022-11-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0009_auto_20221116_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistProduct',
        ),
    ]
